# Render Blueprint
services:
  # Backend API
  - type: web
    name: ai-mixer-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd tournament_webapp && python dev_server.py --production
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.12"
      - key: PRODUCTION
        value: "true"
      - key: MODELS_DIR
        value: "../models/deployment"
      - key: PORT
        value: "10000"
      - key: HOST
        value: "0.0.0.0"
